### PR TITLE
add code to store number of supervisors in Redis

### PR DESCRIPTION
**Pull request by minh-adimian**
Store the number of supervisors in Redis and update them based on event of new supervisors run or supervisors crashes

### CODE REVIEW

**Comment by PierreSavatte** [comment]
Instead of storing in Redis a integer, we could store a set with the names of the Supervisors, what do you think?

**Comment by minh-adimian** [comment]
Yes that would be more informative. I'll work on it

**Comment by minh-adimian** [comment]
It's done. In fact I don't know if it is necessary to also store arbiters and their running jobs so in case we have new leader, we would know which job should be rerun (since now we do Arbiters on demand). What do you think?

**Comment by PierreSavatte** [comment]
> It's done. In fact I don't know if it is necessary to also store arbiters and their running jobs so in case we have new leader, we would know which job should be rerun (since now we do Arbiters on demand). What do you think?

We discussed that subject last time and arrived to that proposition : when a deamon job need to be executed, every Supervisor will run an Arbiter running that job.
In this scenario, no need to store which Arbiter needs to be re-run.

**Comment by minh-adimian** [comment]
Oki :)

**Pull request closed without merging**
